services:
  - type: web
    name: islaapp
    runtime: node
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
    rootDir: open-pro-next
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 22.13.0
      - key: NODE_ENV
        value: production
